version: "3.8"

services:
  trainer-workload-service:
    build:
      context: ./trainer-workload-service
    ports:
      - 8089:8080
    networks:
      - app-network
    depends_on:
      - mongo
      - service-registry
    container_name: trainer-workload-service

  service-registry:
    build:
      context: ./service-registry
    ports:
      - 8761:8761
    networks:
      - app-network
    container_name: service-registry

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      app-network:
    volumes:
      - mongo-data:/data/db
    container_name: mongo

networks:
  app-network:

volumes:
  mongo-data: